### ISSUE TITLE
Crear servidor, TAREA 13

### ISSUE THREAD

**Issue by arh09** [gti-sos/SOS1920-11#4]
'Added an stupid description'

**Comment by IgnacioCVGitHub** [comment]
Okey yo he acabado de hacerlo en mi servidor privado y ya lo tengo listo. Espero que ustedes lo acabeis para el jueves. saludos

**Comment by arh09** [comment]
Yo acabo de echarle un vistazo, y devuelvo la hora por consola porque creo una fecha en el mismo instante que  se inicia el servidor, pero no he sido capaz de tomar la hora de servidor express. Ayuda? Yo seguiré bicheando de  todas formas.

**Comment by arh09** [comment]
reopened to add description
